export { getSchoolCatalog, fetchSchoolCatalog, getCatalogApiUrl, getContactApiUrl, getSchoolCatalogSlug } from "@/lib/catalog/fetch";
export type { PublicSchoolCatalog } from "@/lib/catalog/types";
export {
  buildAddonsDisplayFromCatalog,
  buildAdultPackagesFromCatalog,
  buildClassSessionsFromCatalog,
  buildDriverEdPackagesFromCatalog,
  buildEnrollmentCatalogState,
  buildHomeBatchCards,
  buildLessonFacts,
  buildLessonsFromCatalog,
  buildLiveSite,
  buildScheduledClassFacts,
  buildTeenPackageFacts,
  buildTeenPackagesFromCatalog,
  getCatalogLessonPrice,
  getCatalogPriceLabel,
  legacyProductIdForName,
  parseCustomerIncludes,
  resolveLiveEnrollmentProduct,
  todayIsoDate,
  type CatalogAddonDisplay,
  type CatalogDisplayPackage,
  type CatalogLessonDisplay,
  type CatalogLessonFact,
  type HomeBatchCard,
  type LiveSiteData,
  type ScheduledClassFact,
} from "@/lib/catalog/map";
export {
  buildPublicEnrollUrl,
  getPublicEnrollBaseUrl,
  getPublicEnrollSchoolSlug,
  resolveCatalogPackageId,
} from "@/lib/catalog/publicEnrollUrl";
